<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Home'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendName('format-detection', 'telephone=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->appendStylesheet($this->basePath('css/grid.css'))
                        ->appendStylesheet($this->basePath('css/style.css'))
                        ->appendStylesheet($this->basePath('css/booking.css'))
                        ->appendStylesheet($this->basePath('css/jquery.fancybox.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->appendFile($this->basePath('js/jquery.js'))
            ->appendFile($this->basePath('js/jquery-migrate-1.2.1.js'))
            ->appendFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath('js/device.min.js'))
        ; ?>

    </head>
    <body>
    <div class="page">


        <?= $this->content ?>

        <!--========================================================
                                  FOOTER
        =========================================================-->
        <footer>
            <? /* ?>
            <div class="well bg-2">
                <section class="section-8">
                    <ul>
                        <li>
                            <a href='#'><span class="fa fa-facebook"></span></a>
                        </li>
                        <li>
                            <a href='#'><span class="fa fa-twitter"></span></a>
                        </li>
                        <li>
                            <a href='#'><span class="fa fa-skype"></span></a>
                        </li>
                        <li>
                            <a href='#'><span class="fa fa-google-plus"></span></a>
                        </li>
                        <li>
                            <a href='#'><span class="fa fa-instagram"></span></a>
                        </li>
                        <li>
                            <a href='#'><span class="fa fa-vimeo-square"></span></a>
                        </li>
                    </ul>
                </section>
            </div>
            <div class="well bg-3">
                <section class="section-9 container" id="subscribe">
                    <div class="box">
                        <h3>Subscribe</h3>

                        <form id="subscribe-form" class="subscribe-form">
                            <div class="success">Your subscription request has been sent!</div>
                            <label class="email">
                                <input type="email" value="Enter your email">
                                <span class="error">*Invalid email.</span>
                            </label>
                            <a data-type="submit" href="#" class="btn">Subscribe</a>
                        </form>
                    </div>
                </section>
            </div>
            <? */ ?>
            <div class="container">
                <div class="copyright">
                    <em>
                        <a href="../"><span class="icon flaticon-cup55"></span> bespoke apps</a>
                    </em>
                    © <span id="copyright-year"></span> |
                    Company Number: 08987055 |
                    VAT Number: GB184942963 |
                    <a href="#">Privacy Policy</a>
                    <!-- {%FOOTER_LINK} -->
                </div>
            </div>
        </footer>
    </div>
    <?php echo $this->inlineScript() ?>
    <script src="js/script.js"></script>
    </body>
</html>
