<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Home'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendName('format-detection', 'telephone=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->appendStylesheet($this->basePath('css/grid.css'))
                        ->appendStylesheet($this->basePath('css/style.css'))
                        ->appendStylesheet($this->basePath('css/booking.css'))
                        ->appendStylesheet($this->basePath('css/jquery.fancybox.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->appendFile($this->basePath('js/jquery.js'))
            ->appendFile($this->basePath('js/jquery-migrate-1.2.1.js'))
            ->appendFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath('js/device.min.js'))
        ; ?>

    </head>
    <body>
    <div class="page">
        <!--========================================================
                                  HEADER
        =========================================================-->
        <header id="home">
            <div class="header_panel">
                <div class="container">
                    <div class="brand">
                        <h1 class="brand_name"><a href="../"><span class="icon flaticon-cup55"></span>bespoke apps</a></h1>
                        <p class="brand_slogan">Your apps the way you want them</p>
                    </div>
                </div>
            </div>

            <div class="container">
                <div class="row">
                    <div class="grid_6">
                        <div class="box-1">
                            <h2><em>Create great websites </em><br>fast with us!</h2>
                            <ul class="marked-list">
                                <li>
                                    <h3><a href="#">You tell us what you need</a></h3>
                                    <p>Whether it be a contact form, news ticker or administration portal &ndash; no job is too big or small. You tell us exactly what you want. You are in control.</p>
                                </li>
                                <li>
                                    <h3><a href="#">We will discuss your requirements</a></h3>
                                    <p>Along with your budget we will discuss how to get the most out of your requirements. We want to understand as much as possible about your needs so we can WOW you.</p>
                                </li>
                                <li>
                                    <h3><a href="#">You will receive you high quality app ready to use</a></h3>
                                    <p>Get ready to be amazed! All our projects come fully tested (with unit tests where applicable) and will work in IE, Firefox, Chrome and Safari.</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="grid_6 bg-1">
                        <div class="box-2">
                            <h2>Request a quote now!</h2>
                            <p>Send us as much information as possible so we can assist you.</p>
                            <form id="bookingForm" class="booking-form">
                                <div class="tmInput">
                                    <input name="Name" placeHolder="Name" type="text" data-constraints='@NotEmpty @Required @AlphaSpecial'>
                                </div>
                                <div class="tmInput">
                                    <input name="Email:" placeHolder="E-mail:" type="text" data-constraints='@NotEmpty @Required @Email'>
                                </div>
                                <div class="tmTextarea">
                                    <textarea name="Details" placeHolder="Details" data-constraints='@NotEmpty @Required' rows="7"></textarea>
                                </div>
                                <a href="#" class="btn" data-type="submit">Get a quote!</a>
                            </form>

                        </div>
                    </div>
                </div>
            </div>

        </header>
        <!--========================================================
                                  CONTENT
        =========================================================-->

        <?= $this->content ?>

        <!--========================================================
                                  FOOTER
        =========================================================-->
        <footer>
            <div class="well bg-2">
                <section class="section-8">
                    <ul>
                        <li>
                            <a href='#'><span class="fa fa-facebook"></span></a>
                        </li>
                        <li>
                            <a href='#'><span class="fa fa-twitter"></span></a>
                        </li>
                        <li>
                            <a href='#'><span class="fa fa-skype"></span></a>
                        </li>
                        <li>
                            <a href='#'><span class="fa fa-google-plus"></span></a>
                        </li>
                        <li>
                            <a href='#'><span class="fa fa-instagram"></span></a>
                        </li>
                        <li>
                            <a href='#'><span class="fa fa-vimeo-square"></span></a>
                        </li>
                    </ul>
                </section>
            </div>
            <div class="well bg-3">
                <section class="section-9 container" id="subscribe">
                    <div class="box">
                        <h3>Subscribe</h3>

                        <form id="subscribe-form" class="subscribe-form">
                            <div class="success">Your subscription request has been sent!</div>
                            <label class="email">
                                <input type="email" value="Enter your email">
                                <span class="error">*Invalid email.</span>
                            </label>
                            <a data-type="submit" href="#" class="btn">Subscribe</a>
                        </form>
                    </div>
                </section>
            </div>
            <div class="container">
                <div class="copyright">
                    <em>
                        <a href="../"><span class="icon flaticon-cup55"></span> wrico</a>
                    </em>
                    © <span id="copyright-year"></span> |
                    <a href="#">Privacy Policy</a>
                    <!-- {%FOOTER_LINK} -->
                </div>
            </div>
        </footer>
    </div>
    <?php echo $this->inlineScript() ?>
    <script src="js/script.js"></script>
    </body>
</html>
