<main>
    <div class="well bg-1">
        <section class="section-1 container" id="about">
            <div class="row">
                <div class="grid_4">
                    <div class="box-3">
                        <div class="icon flaticon-notebook79"></div>
                        <h3><a href='#'>Responsive Design</a></h3>
                        <p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
                    </div>
                </div>
                <div class="grid_4">
                    <div class="box-3">
                        <div class="icon flaticon-hand226"></div>
                        <h3><a href='#'>Cross-Browser Support</a></h3>
                        <p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
                    </div>
                </div>
                <div class="grid_4">
                    <div class="box-3">
                        <div class="icon flaticon-bulb19"></div>
                        <h3><a href='#'>Creative Design</a></h3>
                        <p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="grid_4">
                    <div class="box-3">
                        <div class="icon flaticon-gift84"></div>
                        <h3>
                            <a href='#'>Bootstrap 3.1</a>
                        </h3>
                        <p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
                    </div>
                </div>
                <div class="grid_4">
                    <div class="box-3">
                        <div class="icon flaticon-sheet3"></div>
                        <h3>
                            <a href='#'>100 Icon Fonts</a>
                        </h3>
                        <p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
                    </div>
                </div>
                <div class="grid_4">
                    <div class="box-3">
                        <div class="icon flaticon-screwdriver26"></div>
                        <h3>
                            <a href='#'>More Features</a>
                        </h3>
                        <p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <div class="well">
        <section class="section-2 container">
            <div class="row">
                <div class="grid_6">
                    <div class="img"><img src="images/img01.jpg" alt=""/></div>
                </div>
                <div class="grid_6">
                    <h2>Discover the advantages</h2>

                    <p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                        laboris
                        nisi ut aliquip ex ea commodo.</p>
                    <ul>
                        <li>
                            <span class="icon flaticon-password19"></span>
                            <a href='#'>Lorem ipsum dolor sit amet</a>
                        </li>
                        <li>
                            <span class="icon flaticon-message30"></span>
                            <a href='#'>Conse ctetur adipisicing</a>
                        </li>
                        <li>
                            <span class="icon flaticon-setting5"></span>
                            <a href='#'>Elit sed do eiusmod tempor</a>
                        </li>
                        <li>
                            <span class="icon flaticon-briefcase65"></span>
                            <a href='#'>Incididunt ut labore</a>
                        </li>
                    </ul>
                </div>
            </div>
        </section>
        <section class="section-3" id="features">
            <div class="box" data-equal-group="equal-1">
                <div class="icon flaticon-download3"></div>
                <h3><a href='#'>Your Data in Cloud</a></h3>
                <p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo.</p>
            </div>
            <div class="box" data-equal-group="equal-1">
                <div class="icon flaticon-gift84"></div>
                <h3><a href='#'>Monthly Rewards</a></h3>
                <p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo.</p>
            </div>
            <div class="box" data-equal-group="equal-1">
                <div class="icon flaticon-rain2"></div>
                <h3><a href='#'>24/7 Support</a></h3>
                <p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo.</p>
            </div>
        </section>
        <section class="section-4 container" id="pricing">
            <h2>Pricing</h2>

            <div class="row">
                <div class="grid_4">
                    <div class="box" data-equal-group="equal-2">
                        <h3>Elementary</h3>

                        <p><em>$158</em> / month</p>
                        <hr/>
                        <ul class="marked-list">
                            <li><a href='#'>Lorem ipsum dolor sit amet</a></li>
                            <li><a href='#'>Conse ctetur adipisicing</a></li>
                            <li><a href='#'>Elit sed do eiusmod tempor</a></li>
                            <li><a href='#'>Incididunt ut labore</a></li>
                        </ul>
                        <a class="btn" href='#'>Buy now!</a>
                    </div>
                </div>
                <div class="grid_4">
                    <div class="box" data-equal-group="equal-2">
                        <h3>Advanced</h3>

                        <p><em>$178</em> / month</p>
                        <hr/>
                        <ul class="marked-list">
                            <li><a href='#'>Lorem ipsum dolor sit amet</a></li>
                            <li><a href='#'>Conse ctetur adipisicing</a></li>
                            <li><a href='#'>Elit sed do eiusmod tempor</a></li>
                            <li><a href='#'>Incididunt ut labore</a></li>
                        </ul>
                        <a class="btn" href='#'>Buy now!</a>
                    </div>
                </div>
                <div class="grid_4">
                    <div class="box" data-equal-group="equal-2">
                        <h3>Premium</h3>

                        <p><em>$198</em> / month</p>
                        <hr/>
                        <ul class="marked-list">
                            <li><a href='#'>Lorem ipsum dolor sit amet</a></li>
                            <li><a href='#'>Conse ctetur adipisicing</a></li>
                            <li><a href='#'>Elit sed do eiusmod tempor</a></li>
                            <li><a href='#'>Incididunt ut labore</a></li>
                        </ul>
                        <a class="btn" href='#'>Buy now!</a>
                    </div>
                </div>
            </div>
        </section>
        <section class="section-5" id="gallery">
            <h2>Gallery</h2>

            <div class="box">
                <a data-fancybox-group="gallery" class="thumb" href="images/gallery/gallery01.jpg">
                    <img src="images/gallery-thumb01.jpg" alt=""/>
                    <span class="thumb_overlay"></span>
                </a>
                <a data-fancybox-group="gallery" class="thumb" href="images/gallery/gallery02.jpg">
                    <img src="images/gallery-thumb02.jpg" alt=""/>
                    <span class="thumb_overlay"></span>
                </a>
                <a data-fancybox-group="gallery" class="thumb" href="images/gallery/gallery03.jpg">
                    <img src="images/gallery-thumb03.jpg" alt=""/>
                    <span class="thumb_overlay"></span>
                </a>
                <a data-fancybox-group="gallery" class="thumb" href="images/gallery/gallery04.jpg">
                    <img src="images/gallery-thumb04.jpg" alt=""/>
                    <span class="thumb_overlay"></span>
                </a>
            </div>
        </section>
        <section class="section-6 container" id="faqs">
            <h2>FAQs</h2>

            <div class="row">
                <div class="grid_6">
                    <div class="box">
                        <h3>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor.</h3>

                        <p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo. Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                    </div>
                </div>
                <div class="grid_6">
                    <div class="accordion">
                        <h4 class="accordion_header">Lorem ipsum dolor sit amet conse cteturuis nostrud </h4>
                        <p class="accordion_cnt">Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo.</p>
                        <h4 class="accordion_header">Adipisicing elit sed do eiusmod tempor</h4>
                        <p class="accordion_cnt">Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo.</p>
                        <h4 class="accordion_header">Incididunt ut labore et dolore magna aliqua</h4>
                        <p class="accordion_cnt">Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo.</p>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <div class="well bg-1">
        <section class="section-7 container" id="testimonials">
            <div class="box">
                <div class="img"><img src="images/img02.jpg" alt=""/></div>
                <p><em>Tom Cooper</em></p>
                <p>Company customer</p>
            </div>
            <blockquote>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.</blockquote>
        </section>
    </div>
</main>